apiVersion: apps/v1
kind: Deployment
metadata:
  name: ready
  namespace: suprith
  labels:
     app: ready
spec:
  selector:
    matchLabels:
      app: ready
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate      
  template:
    metadata:
      labels:
         app: ready
    spec:
       imagePullSecrets: # Add the imagePullsecrets field
        - name: mysecretfile  # Name of the secret created
      containers:
        - name: ready
          image: ready.azurecr.io/ready2.0
          resources:
            requests:
              cpu: 100
              memory: 100Mi
            limits:  # Move limits insidde the resources block
               cpu: 100  
               memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10  
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 80
            initialDelaySeconds: 5
            sucessThreshold: 1
            failureThreshold: 3          
            periodSeconds: 10
