apiVersion: apps/v1
kind: Deployment
metadata:
  name: ready
  namespace: suprith
  labels:
    app: ready
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ready
  template:
    metadata:
      labels:
        app: ready
    spec:
      containers:
      - name: ready
        image: ready.azurecr.io/ready2.0
        ports:
        - containerPort: 5000
      imagePullSecrets:
       - name: ready
