apiVersion: v1
kind: Service
metadata:
  name: docker-app
  namespace: suprith
spec:
  selector:
    app: docker-app
  type: loadbalancer  
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000